services:
  wxread:
    image: ghcr.io/usirukesikam/wxread-docker:latest
    container_name: wxread
    restart: unless-stopped
    env_file:
      - path: ./wxread.env
        format: raw
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
